language: python

python:
  # - "3.2"
  # - "3.3"
  # - "3.4"
  - "3.5"
  # - "3.5-dev" # 3.6 development branch
  # - "3.6"
  # - "3.6-dev" # 3.6 development branch
  # - "nightly" # currently points to 3.7-dev
  # PyPy versions
  # - "pypy3" # Pypy3 2.4.0

before_install:
  - sudo apt-get -y -f install libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-gfx-dev;
  - sudo apt-get -y -f install libpng-dev zlib1g-dev libjpeg-dev libtiff4-dev libportmidi-dev;
  - sudo apt-get -y -f install libx11-6 libX11-dev xfonts-base xfonts-100dpi xfonts-75dpi xfonts-cyrillic
  - sudo apt-get -y -f install xvfb;

install:
  # install library requirements
  - ./install-dependencies.sh
    
  # install python requirements
  - "pip install -r requirements.txt"
  - "pip install coveralls"

before_script:
  - export DISPLAY=:99.0;
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1280x720x24 -ac +extension GLX;
  - export PYTHONPATH=$PYTHONPATH:$(pwd);

# command to run tests
script:
  - export SDL2DIR="/home/travis/sdl2install"
  - export PYSDL2_DLL_PATH="$SDL2DIR/lib"
  - export PATH="$PATH:$PYSDL2_DLL_PATH"
  - coverage run --source=sdl2 setup.py test
  
after_success:
  - coveralls
