language: python

python:
  # - "3.2"
  # - "3.3"
  # - "3.4"
  - "3.5"
  # - "3.5-dev" # 3.6 development branch
  # - "3.6"
  # - "3.6-dev" # 3.6 development branch
  # - "nightly" # currently points to 3.7-dev
  # PyPy versions
  # - "pypy3" # Pypy3 2.4.0
  
before_install:

  # install sdl2-2.0.5 
  - wget https://www.libsdl.org/release/SDL2-2.0.5.tar.gz
  - tar xf SDL2-2.0.5.tar.gz
  - cd SDL2-2.0.5  
  - ./configure
  - make
  - sudo make install
  - cd ..
  
  # install SDL2_image-2.0.1
  - wget https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.1.tar.gz
  - tar xf SDL2_image-2.0.1.tar.gz
  - cd SDL2_image-2.0.1
  - ./configure
  - make
  - sudo make install
  - cd ..
  
  # install SDL2_ttf-2.0.14
  - wget https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.14.tar.gz
  - tar xf SDL2_ttf-2.0.14.tar.gz
  - cd SDL2_ttf-2.0.14
  - ./configure
  - make
  - sudo make install
  - cd ..
  
  # install SDL2_mixer-2.0.1
  - wget https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.1.tar.gz
  - tar xf SDL2_mixer-2.0.1.tar.gz
  - cd SDL2_mixer-2.0.1
  - ./configure
  - make
  - sudo make install
  - cd ..
  
  # install SDL2_gfx-1.0.1
  - wget http://www.ferzkopp.net/Software/SDL2_gfx/SDL2_gfx-1.0.1.tar.gz
  - tar xf SDL2_gfx-1.0.1.tar.gz
  - cd SDL2_gfx-1.0.1
  - ./configure
  - make
  - sudo make install
  - cd ..
  
  # install sdl2-ttf
  # - "sudo apt-get -f -y install libfreetype6"
  
  # - "sudo apt-get -f -y install libsdl2-image-2.0-0"
  # - "sudo apt-get -f -y install libsdl2-gfx-1.0-0"
  # - "sudo apt-get -f -y install libsdl2-ttf-2.0-0"
  # - "sudo apt-get -f -y install libsdl2-mixer-2.0-0"
  # - "sudo apt-get -f -y install libsdl2-net-2.0-0"
  # - wget https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.14.tar.gz
  # - wget http://download.savannah.gnu.org/releases/freetype/freetype-2.7.1.tar.gz
  # - sudo make install
  
  # - export PYSDL2_DLL_PATH="$SDL2DIR/lib"
  # - ls $PYSDL2_DLL_PATH/*.so
  
# command to install dependencies
install:
  # install python requirements
  - "pip install -r requirements.txt"
  
# command to run tests
script: make runtest
