environment:

  matrix:
    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.2"
      PYTHON_ARCH: "32"
init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "powershell appveyor.ps1"

build: off

test_script:
  - "hg clone https://bitbucket.org/dholth/sdl2_lib win"
  - "%WITH_COMPILER% %PYTHON%/python -m pip install cffi apipkg"
  - "%WITH_COMPILER% %PYTHON%/python setup.py bdist_wheel"

artifacts:
  - path: dist\*

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
